---
- name: "test02 - role defaults"
  debug: var=var_test02

- name: "test03 - inventory file or script group vars"
  debug: var=var_test03_{{ item }}
  with_items: [1, 2]

- name: "test04 - inventory group_vars/all"
  debug: var=var_test04_{{ item }}
  with_items: [1, 2]

- name: "test05 - playbook group_vars/all"
  debug: var=var_test05

- name: "test06 - inventory group_vars/*"
  debug: var=var_test06

- name: "test07 - playbook group_vars/*"
  debug: var=var_test07

- name: "test08 - inventory file or script host vars"
  debug: var=var_test08

- name: "test09 - inventory host_vars/*"
  debug: var=var_test09

- name: "test10 - inventory host_vars/*"
  debug: var=var_test10

- name: "test12 - play vars"
  debug: var=var_test12

- name: "test13 - play vars_prompt"
  debug: var=var_test13

- name: "test14 - play vars_files"
  debug: var=var_test14

- name: "test15 - role vars"
  debug: var=var_test15

- block:
  - name: "test16 - block vars"
    debug: var=var_test16
  - name: "test17 - task vars"
    debug: var=var_test17
    vars:
      - var_test17: "This is 'task vars'"
  vars:
    - var_test16: "This is 'block vars'"
    - var_test17: "This is 'block vars'"

- name: "test18 - include_vars - pre"
  include_vars: include_vars_test.yml

- name: "test18 - include_vars"
  debug: var=var_test18
  vars:
    - var_test18: "This is 'task vars'"
