---
- name: "test02 - role defaults"
  debug: var=var_test02

- name: "test03 - inventory file or script group vars"
  debug: var=var_test03_{{ item }}
  with_items: [1, 2]

- name: "test04 - inventory group_vars/all"
  debug: var=var_test04_{{ item }}
  with_items: [1, 2]

- name: "test05 - playbook group_vars/all"
  debug: var=var_test05

- name: "test06 - inventory group_vars/*"
  debug: var=var_test06

- name: "test07 - playbook group_vars/*"
  debug: var=var_test07

- name: "test08 - inventory file or script host vars"
  debug: var=var_test08
